[package]
name = "timebank"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
chrono = { varsion = "0.4.23", features = ["serde"] }
rusqlite = "0.28.0"
