[package]
name = "timebank_db"
version = "0.1.0"
edition = "2021"

[dependencies]
timebank_core = { path = "../timebank_core" }
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "1", features = ["full"] }
